services:
  bot:
    build: .
    env_file:
      - .env
    restart: always
    network_mode: host
    volumes:
      - ./app/log/logs:/usr/src/m_bot/app/log/logs
      - ./app/extra:/usr/src/m_bot/app/extra